spring:
  profiles:
    active: default

endpoints:
  shutdown:
    enabled: true

---

spring:
  profiles: default

---

spring:
  profiles: local

spring.data.mongodb:
  database: demo
  host: dockerhost
  port: 27017
  repositories.enabled: true
  username: admin

